name: CI
on: [push]
jobs:
  lhci:
    name: Lighthouse CI - testing1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use node.js 10.x 
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: npm install, build
        run: |
          yarn 
          npm run build
      - name: run lighthouse CI
        run: |
          npm install -g @lhci/cli@0.3.x 
          lhci autorun --upload.target=temporary-public-storage || echo "LHCI failed!"
        env: 
          LHCI_GITHUB_APP_TOKEN: ${{secrets.LIGHTHOUSE_APP_TOKEN}}